# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/dolskTyresProject
spring.datasource.username=postgres
spring.datasource.password=Prodolsk7
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd

server.error.include-message=always
server.error.include-binding-errors=always

server.address=0.0.0.0
server.port=8080

# JWT Configuration
jwt.secret=my-super-secret-key-that-is-very-long1959
#jwt.expiration=3600000
jwt.expiration=604800000

cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:8081}

logging.level.org.springframework.security=INFO
